# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 target 'WeiXinProject' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'LFDBusFrameWork'
    pod 'Masonry'
    pod "textFrameWork"
    pod “NetworkFrameWork”
    pod “HyphenateLite”
end
source 'http://gitlab-jr.letv.cn/iosteam/lefinancepods.git'
source 'https://github.com/CocoaPods/Specs.git'
source ‘https://git.oschina.net/hahah_/specresposity.git’


