# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 target 'WeiXinProject' do
    pod 'AFNetworking'
    pod 'Mantle'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'LeNetworkFrame'
    pod 'LFDBusFrameWork'
    pod 'Masonry'
end
source 'http://gitlab-jr.letv.cn/iosteam/lefinancepods.git'
source 'https://github.com/CocoaPods/Specs.git'


